### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by Suntrie** [EinTheDog/Kurs1var15#2]
1. Протестируйте, пожалуйста, в том числе и ситуации, когда "что-то пошло не так" - например, попытку вставить символ в занятую клетку, очистить свободное поле, et cetera;

2. getTheLongestComb стоит разбить на отдельные тестовые сценарии (разнести их по отдельным тестовым методам) со значащими именами.

**Comment by EinTheFrog** [comment]
Тесты, где "что-то идет не так" добавил, getTheLongestComb разбил на 2 тестовых сценария

**Comment by Suntrie** [comment]
Sic. У меня на Mint сейчас Ваши тесты падают (потому что System.delimiter).

**Comment by EinTheFrog** [comment]
Проглазел этот момент. Теперь все должно работать

**Comment by Suntrie** [comment]
Буду готова посмотреть поправки и скорректировать оценку после сдачи второй работы - не забудьте, пожалуйста, до меня дойти/ написать.
